alter table public.students
add column if not exists form_received_date date,
add column if not exists form_submitted_date date,
add column if not exists student_name_bn text,
add column if not exists student_name_en text,
add column if not exists birth_certificate_no text,
add column if not exists date_of_birth date,
add column if not exists age_day integer,
add column if not exists age_month integer,
add column if not exists age_year integer,
add column if not exists gender text,
add column if not exists residential_type text,
add column if not exists father_name_bn text,
add column if not exists father_name_en text,
add column if not exists father_nid text,
add column if not exists father_mobile_1 text,
add column if not exists father_mobile_2 text,
add column if not exists father_mobile_3 text,
add column if not exists father_whatsapp_number text,
add column if not exists father_occupation text,
add column if not exists father_profession_type text,
add column if not exists father_profession_details text,
add column if not exists father_education text,
add column if not exists mother_name_bn text,
add column if not exists mother_name_en text,
add column if not exists mother_nid text,
add column if not exists mother_mobile text,
add column if not exists mother_mobile_1 text,
add column if not exists mother_mobile_2 text,
add column if not exists mother_occupation text,
add column if not exists mother_profession_type text,
add column if not exists mother_education text,
add column if not exists present_village text,
add column if not exists present_post_office text,
add column if not exists present_post_code text,
add column if not exists present_upazila text,
add column if not exists present_district text,
add column if not exists permanent_village text,
add column if not exists permanent_post_office text,
add column if not exists permanent_post_code text,
add column if not exists permanent_upazila text,
add column if not exists permanent_district text,
add column if not exists docs_birth_certificate boolean default false,
add column if not exists docs_previous_marksheet boolean default false,
add column if not exists docs_guardian_photo boolean default false,
add column if not exists docs_guardian_nid boolean default false,
add column if not exists same_as_present_address boolean default false;
